export enum UserRoleType {
    ADMIN_GLOBAL = 'ADMIN_GLOBAL',
    ADMIN_COUNTRY = 'ADMIN_COUNTRY',
    ADMIN_SITE = 'ADMIN_SITE',    
    STRENNE_USER = 'STRENNE_USER' , 
    STRENNE_OPERATOR = 'STRENNE_OPERATOR' , 
    STRENNE_ADMIN = 'STRENNE_ADMIN' , 
}
